---
version: 0.2
# Buildspec Reference Doc:
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-syntax

#################################
# Runtime Environment Variables #
#################################

env:
  git-credential-helper: yes
  secrets-manager:
    NPM_REGISTRY_TOKEN: /services/github/npm/token
  exported-variables:
    - VERSION_NUMBER
    - VERSION_TAG
  shell: bash

#######################################################################
# Sequence of commands CodeBuild runs during each phase of the build. #
#######################################################################

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # Use Install phase to install packages or any pre-reqs you may need throughout the build (e.g. dev deps, security checks, etc.)
      - echo "[Setting up Git for codebuild]"
      - aws s3 cp s3://cloud-ops-tools/increment-version.sh increment-version.sh
      - chmod a+x ./increment-version.sh
      - echo "[Getting tags]"
      - export LAST_VERSION_TAG=$(git tag | grep -E "^$GITHUB_TAG_PREFIX-[0-9]" | sort -V | tail -1)
      - export LAST_VERSION_TAG=${LAST_VERSION_TAG:-"$GITHUB_TAG_PREFIX-0.0.0.0"}
      - echo $LAST_VERSION_TAG
      - export VERSION_TAG=$(./increment-version.sh $LAST_VERSION_TAG patch)
      - echo $VERSION_TAG
      - export VERSION_NUMBER=${VERSION_TAG:$((${#GITHUB_TAG_PREFIX} + 1))}
      - echo $VERSION_NUMBER
      - echo "[Install phase]"
      - export NPM_TOKEN=$NPM_REGISTRY_TOKEN
      - cd $CDK_APP_DIRECTORY
      - yarn
    finally:
      - echo "Completed installing nodejs 16"
  build:
    commands:
      - echo "[Build phase]"
      - yarn build
      - yarn test
      - yarn cdk synth
      - export CDK_FOLDER=cdk.out
      - ls $CDK_FOLDER
      - zip -r $CDK_APP_NAME.zip $CDK_FOLDER/*
      # us-west-2
      - aws s3 cp $CDK_APP_NAME.zip s3://$BUILD_OUTPUT_BUCKET_WEST/$BUILD_OUTPUT_PATH/$VERSION_TAG.zip --sse aws:kms --sse-kms-key-id $BUILD_KMS_KEY_ID_WEST
      # us-east-1
      - aws s3 cp $CDK_APP_NAME.zip s3://$BUILD_OUTPUT_BUCKET_EAST/$BUILD_OUTPUT_PATH/$VERSION_TAG.zip --sse aws:kms --sse-kms-key-id $BUILD_KMS_KEY_ID_EAST
  post_build:
    commands:
      # # Use Post Build for notifications, git tags and any further customization after build
      - echo "[Post-Build phase - doing nothing]"

artifacts:
  base-directory: ./$CDK_APP_DIRECTORY
  files:
    - 'cdk.out/**/*'
